apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confighub

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: confighub
  app.kubernetes.io/version: "1.0.0"
